### ISSUE TITLE
YogaSMC

### ISSUE THREAD

**Issue by Rxxbertx** [kalkmann/Legion-5600H-Hackintosh#10]
Why don't you use that kext? I have the lenovo legion 5 pro with a ryzen 7 5800h and it doesn't work for me The touchpad, the brightness control (I tried your efi and nothing...)

**Comment by kalkmann** [comment]
> Why don't you use that kext? I have the lenovo legion 5 pro with a ryzen 7 5800h and it doesn't work for me The touchpad, the brightness control (I tried your efi and nothing...)

I haven't tested it yet. But since my laptop is a Legion with a dedicated 6600m, I can't expect too much battery life. As my goal is performance with mobility, the rest is irrelevant.

I use this kext for I2C in this particular laptop:
https://nootinc.github.io/Extras/Kexts/VoodooI2C.zip

Native brightness control in keyboard don´t work. Use (same behavior):
https://lunar.fyi/

**Comment by Rxxbertx** [comment]
That kext doesn't work for me, could it be because it's the pro model and they change parts?

**Comment by Rxxbertx** [comment]
That kext doesn't work for me, could it be because it's the pro model and they change parts?

**Comment by kalkmann** [comment]
> 
could it be. But in my experiences, ssdt-hpet conflicted. Check if this is your case.

<img width="1007" alt="image" src="https://github.com/kalkmann/Legion-5600H-Hackintosh/assets/8891448/ad80a793-5523-4f46-b03d-3817c0a06d3a">

**Comment by Rxxbertx** [comment]
Wow what, u quit SSDT HPET AND WORKS?? SLEEP WORKS?

**Comment by Rxxbertx** [comment]
But thats weird, is a HID device, why is there an ELAN? Hpet should fix conflicts 😂

**Comment by kalkmann** [comment]
> Wow what, u quit SSDT HPET AND WORKS?? SLEEP WORKS?

These laptops barely booted in January/23.

Roberto, you are (very) welcome to help solve our problems with AMD laptops. Do you speak Portuguese?

**Comment by Rxxbertx** [comment]
I speak spanish 👌

**Comment by kalkmann** [comment]
> I speak spanish 👌

Since everything is detailed in git, sleep doesn't work. Up until 2 weeks ago, the laptop would not boot with the 2 USB controllers enabled. A good soul updated a kext to make it work (GUX-RyzenXHCIFix).

About sleep, there are TSC issues at kernel level (we used a patch for boot).

**Comment by Rxxbertx** [comment]
Yeeh but in my lenovo pro That new kext doesn't work :(

**Comment by Rxxbertx** [comment]
What patch do u use, check YogaSMC maybe that fixes SLEEP bcz yogaSMC enable mac to write in ec (i think)

**Comment by kalkmann** [comment]
> Yeeh but in my lenovo pro That new kext doesn't work :(

check this in Windows

**Comment by kalkmann** [comment]
> What patch do u use, check YogaSMC maybe that fixes SLEEP bcz yogaSMC enable mac to write in ec (i think)

yep, in plans. Thanks

**Comment by Rxxbertx** [comment]
> > Yeeh but in my lenovo pro That new kext doesn't work :(
> 
> check this in Windows (model/hardware id)

? What do you mean?

**Comment by Rxxbertx** [comment]
> > What patch do u use, check YogaSMC maybe that fixes SLEEP bcz yogaSMC enable mac to write in ec (i think)
> 
> do you know if kext is for intel or amd based laptops?

Both

**Comment by kalkmann** [comment]
> > > Yeeh but in my lenovo pro That new kext doesn't work :(
> > 
> > 
> > check this in Windows (model/hardware id)
> 
> ? What do you mean?

https://github.com/kalkmann/Legion-5600H-Hackintosh/issues/7

**Comment by Rxxbertx** [comment]
Oh i see, you try using Elan plugin  instead HID? (Idk)

**Comment by kalkmann** [comment]
I tested it now with your kext suggestion (YogaSMC). The system boots normally, but the trackpad didn't work here either.

**Comment by kalkmann** [comment]
> Oh i see, you try using Elan plugin instead HID? (Idk)

You need to know your hardware, for start.

**Comment by Rxxbertx** [comment]
Yep i have the same HID, elan06fa

**Comment by kalkmann** [comment]
> Yep i have the same HID, elan06fa

so (theoretically) you could use the same EFI, modifying the first 3 kernel patches (core count) from 06 to 08 (https://github.com/AMD-OSX/AMD_Vanilla) and insert your own smbios serial information ( https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#using-gensmbios).

**Comment by Rxxbertx** [comment]
> > Yep i have the same HID, elan06fa
> 
> so (theoretically) you could use the same EFI, modifying the first 3 kernel patches (core count) from 06 to 08 (https://github.com/AMD-OSX/AMD_Vanilla) and insert your own smbios serial information ( https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#using-gensmbios).

Hey, u cant sleep? Or u cant wake after sleep?

**Comment by kalkmann** [comment]
> > > Yep i have the same HID, elan06fa
> > 
> > 
> > so (theoretically) you could use the same EFI, modifying the first 3 kernel patches (core count) from 06 to 08 (https://github.com/AMD-OSX/AMD_Vanilla) and insert your own smbios serial information ( https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#using-gensmbios).
> 
> Hey, u cant sleep? Or u cant wake after sleep?

it depends on several factors (kext/patchs combination)... It already went into sleep, but when wakes, it came back with the totally wrong date (years/months ahead) and the system hangs, forcing the restart.

It's probably a result of the patches to resolve the TSC issues, but I don't know.

**Comment by Rxxbertx** [comment]
> > > > Yep i have the same HID, elan06fa
> > > 
> > > 
> > > so (theoretically) you could use the same EFI, modifying the first 3 kernel patches (core count) from 06 to 08 (https://github.com/AMD-OSX/AMD_Vanilla) and insert your own smbios serial information ( https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#using-gensmbios).
> > 
> > Hey, u cant sleep? Or u cant wake after sleep?
> 
> it depends on several factors (kext/patchs combination)... It already went into sleep, but when wakes, it came back with the totally wrong date (years/months ahead) and the system hangs, forcing the restart.
> 
> It's probably a result of the patches to resolve the TSC issues, but I don't know.

No bro, i have the exact same issue, i think is more like a igpu issues or a cpu issue , bcz other people with the U version of CPU they can sleep and wake...
(Mine also reboots by kernel panic after sleep)

**Comment by kalkmann** [comment]
> > > > > Yep i have the same HID, elan06fa
> > > > 
> > > > 
> > > > so (theoretically) you could use the same EFI, modifying the first 3 kernel patches (core count) from 06 to 08 (https://github.com/AMD-OSX/AMD_Vanilla) and insert your own smbios serial information ( https://dortania.github.io/OpenCore-Post-Install/universal/iservices.html#using-gensmbios).
> > > 
> > > 
> > > Hey, u cant sleep? Or u cant wake after sleep?
> > 
> > 
> > it depends on several factors (kext/patchs combination)... It already went into sleep, but when wakes, it came back with the totally wrong date (years/months ahead) and the system hangs, forcing the restart.
> > It's probably a result of the patches to resolve the TSC issues, but I don't know.
> 
> No bro, i have the exact same issue, i think is more like a igpu issues or a cpu issue , bcz other people with the U version of CPU they can sleep and wake... (Mine also reboots by kernel panic after sleep)

TSC issue is from CPU. "IGPU" in mine is off.
