### ISSUE TITLE
Is it compatible with MSI Alpha 17 B5EEK 031VN version?

### ISSUE THREAD

**Issue by HoanNguyen135** [kalkmann/Legion-5600H-Hackintosh#11]
My configuration :
![image](https://github.com/kalkmann/Legion-5600H-Hackintosh/assets/108046905/cad89ee8-741a-446a-885d-6bcd1529ebda)

**Comment by HoanNguyen135** [comment]
Hope you reply soon.Thank you

**Comment by kalkmann** [comment]
> Hope you reply soon.Thank you

Prossibly. To start, modify the AMD kernel patches (core count) for your processor (8 core) in config.plist Info: https://github.com/AMD-OSX/AMD_Vanilla

Maybe the Wifi card (change it for an Intel compatible) and Lan card won't work.

I'm in the GMT -3 time zone...

**Comment by HoanNguyen135** [comment]
> > Hope you reply soon.Thank you
> 
> Prossibly. To start, modify the AMD kernel patches (core count) for your processor (8 core) in config.plist Info: https://github.com/AMD-OSX/AMD_Vanilla
> 
> Maybe the Wifi card (change it for an Intel compatible) and Lan card won't work.
> 
> I'm in the GMT -3 time zone...

thank for your reply

**Comment by HoanNguyen135** [comment]
> > Hope you reply soon.Thank you
> 
> Prossibly. To start, modify the AMD kernel patches (core count) for your processor (8 core) in config.plist Info: https://github.com/AMD-OSX/AMD_Vanilla
> 
> Maybe the Wifi card (change it for an Intel compatible) and Lan card won't work.
> 
> I'm in the GMT -3 time zone...

Thank you for your reply
I turned off the wifi function but my laptop can't disable the onboard graphic card in bios. I booted the hackintosh but it's very lag

**Comment by kalkmann** [comment]
> > > Hope you reply soon.Thank you
> > 
> > 
> > Prossibly. To start, modify the AMD kernel patches (core count) for your processor (8 core) in config.plist Info: https://github.com/AMD-OSX/AMD_Vanilla
> > Maybe the Wifi card (change it for an Intel compatible) and Lan card won't work.
> > I'm in the GMT -3 time zone...
> 
> Thank you for your reply I turned off the wifi function but my laptop can't disable the onboard graphic card in bios. I booted the hackintosh but it's very lag

If you don't have the Switch MUX to isolate the 6600M, my EFI won't help much.

You have to look for other users on the same platform to find out what the solution is, if it is possible to disable something by SSDT or if you can use https://chefkissinc.github.io/nred (APU integrated graphics only).

**Comment by HoanNguyen135** [comment]
> 

thank you for your help
