### ISSUE TITLE
No WhateverGreen included

### ISSUE THREAD

**Issue by traffnoob** [kalkmann/Legion-5600H-Hackintosh#14]
Please add WhateverGreen.kext
After i added this kext, still can't boot because i2c error, kexts must be in the correct order in config.plist

**Comment by kalkmann** [comment]
> Please add WhateverGreen.kext After i added this kext, still can't boot because i2c error, kexts must be in the correct order in config.plist

Add WG kext for...?

What is your BIOS version?

**Comment by traffnoob** [comment]
> Add WG kext for...?

For EFI work? How we boot without them? It's not necessary?

**Comment by traffnoob** [comment]
> What is your BIOS version?
G9CN33WW, it's can't boot with this bios?

**Comment by kalkmann** [comment]
> > Add WG kext for...?
> 
> For EFI work? How we boot without them? It's not necessary?

I wouldn't publish the EFI if it didn't work.

Navi 23 GPUs are assumed to work OOB. The 6600M shares the same Hardware ID as the desktop cards.

Here it works perfectly, as described in the readme.

**Comment by kalkmann** [comment]
> > What is your BIOS version?
> 
> G9CN33WW, it's can't boot with this bios?

https://github.com/kalkmann/Legion-5600H-Hackintosh/issues/6#issuecomment-1643873994

**Comment by traffnoob** [comment]
I downgraded to G9CN32WW and generated smbios, reset nvram, still can't boot
![IMG_20231024_213938_lmc8 4 21 06 22](https://github.com/kalkmann/Legion-5600H-Hackintosh/assets/133532539/ea535994-329d-4d99-99b0-25eec7555045)

**Comment by traffnoob** [comment]
Can you share your telegram or discord?

**Comment by kalkmann** [comment]
> I downgraded to G9CN32WW and generated smbios, reset nvram, still can't boot ![IMG_20231024_213938_lmc8 4 21 06 22](https://user-images.githubusercontent.com/133532539/277756059-ea535994-329d-4d99-99b0-25eec7555045.jpg)

In the BIOS options are you using only the dGPU?

Are you using my EFI? If not, please post yours in a cloud so I can take a look.

**Comment by traffnoob** [comment]
this screenshot with your EFI, yes i using only dGPU

**Comment by kalkmann** [comment]
> this screenshot with your EFI, yes i using only dGPU

If it's exactly the same model (with 6 cores), with the same version and options in the bios, I have no idea what could be preventing it from booting.

**Comment by traffnoob** [comment]
I have work efi for me, but want using your because there 0.9.5 OC.  This is old @ExtremeXT config with ACPI patch that disable first nvme slot bcz have not supported one installed, updated OC to 0.9.4 and add usbfix and airport wifi/bt, this work for me. Can you look into difference between this and yours? I'm not big specialist in hackintosh and wanted just upgrade to 0.9.5 :)
https://drive.google.com/file/d/1xNFH6rL7Yxc7wAn39EvJzW6oTaOUdXOy/view?usp=sharing
upload to google drive due github 25mb limit

**Comment by traffnoob** [comment]
and yes this is same 5600h model, with same intel ax200

**Comment by ExtremeXT** [comment]
@kalkmann Hey, can you check your DMs?

**Comment by kalkmann** [comment]
> I have work efi for me, but want using your because there 0.9.5 OC. This is old @ExtremeXT config with ACPI patch that disable first nvme slot bcz have not supported one installed, updated OC to 0.9.4 and add usbfix and airport wifi/bt, this work for me. Can you look into difference between this and yours? I'm not big specialist in hackintosh and wanted just upgrade to 0.9.5 :) https://drive.google.com/file/d/1xNFH6rL7Yxc7wAn39EvJzW6oTaOUdXOy/view?usp=sharing upload to google drive due github 25mb limit

requested access (when uploading to Google Drive, leave it free for whoever has the link)

**Comment by traffnoob** [comment]
Updated access

**Comment by kalkmann** [comment]
> I have work efi for me, but want using your because there 0.9.5 OC. This is old @ExtremeXT config with ACPI patch that disable first nvme slot bcz have not supported one installed, updated OC to 0.9.4 and add usbfix and airport wifi/bt, this work for me. Can you look into difference between this and yours? I'm not big specialist in hackintosh and wanted just upgrade to 0.9.5 :) https://drive.google.com/file/d/1xNFH6rL7Yxc7wAn39EvJzW6oTaOUdXOy/view?usp=sharing upload to google drive due github 25mb limit

give it a try without the I2C kexts (touchpad)

**Comment by kalkmann** [comment]
Updated yours to 0.9.6 (dev), check if this works: https://drive.google.com/drive/folders/1Qswthj6Ct5QvxYtw6KvlkniDUBA1lTq2?usp=drive_link

**Comment by traffnoob** [comment]
Yes thats 0.9.6 works, thanks!
