### ISSUE TITLE
Lenvo Legion 5 15ARH05H

### ISSUE THREAD

**Issue by MostafaMohamed2002** [kalkmann/Legion-5600H-Hackintosh#18]
i have Lenvo Legion 5 15ARH05H with ryzen 5 4600h and gtx1660ti can this efi config run on it ?

**Comment by kalkmann** [comment]
> i have Lenvo Legion 5 15ARH05H with ryzen 5 4600h and gtx1660ti can this efi config run on it ?

No. Find one with dgpu disabled + igpu enabled with nootedred kext.
