### ISSUE TITLE
Rx5500m support 

### ISSUE THREAD

**Issue by cosmicwanderer7** [kalkmann/Legion-5600H-Hackintosh#19]
I have HP Victus laptop with RX5500M GPU and ryzen 5 5600h will it work?

**Comment by kalkmann** [comment]
Have MUX Switch (can disable igpu on bios)?

**Comment by cosmicwanderer7** [comment]
No mux switch and no options in BIOS. I found another EFI file that worked with nootedred, but Wi-Fi and Bluetooth don't work. Also now, I think it's just using i GPU.
