### ISSUE TITLE
About the processor

### ISSUE THREAD

**Issue by ChenZesen** [kalkmann/Legion-5600H-Hackintosh#20]
Why does your "About this machine" show that the processor is Amd r5 6600h while mine shows intel i7?

**Comment by kalkmann** [comment]
The print is before the patch to resolve the system updates https://github.com/5T33Z0/OC-Little-Translated/blob/main/S_System_Updates/Fixing_System_Updates.md introducing this behavior of bringing the name of an intel processor in the mentioned window. Invalidated the previous (cosmetic) solution cpu-name https://github.com/corpnewt/CPU-Name
