### ISSUE TITLE
Brand: Lenovo Model: Legion 5 6th Gen CPU: AMD Ryzen 7 5800h GPU: AMD Radeon RX 6600m Can you use your efi

### ISSUE THREAD

**Issue by Ghost-Cavendish** [kalkmann/Legion-5600H-Hackintosh#21]
Brand: Lenovo Model: Legion 5 6th Gen CPU: AMD Ryzen 7 5800h GPU: AMD Radeon RX 6600m Can you use your efi

**Comment by ChenZesen** [comment]
![IMG_0669](https://github.com/kalkmann/Legion-5600H-Hackintosh/assets/23404332/71c796ee-e533-4dad-8eee-3a0e8ad21140)
是的，我已经安装完成😊

**Comment by kalkmann** [comment]
> Brand: Lenovo Model: Legion 5 6th Gen CPU: AMD Ryzen 7 5800h GPU: AMD Radeon RX 6600m Can you use your efi

With the adjustments to CPU core number related patches/ssdt, perfectly viable (mine is 6C/12T). I have commented in readme...

**Comment by Ghost-Cavendish** [comment]
> ![IMG_0669](https://private-user-images.githubusercontent.com/23404332/300893358-71c796ee-e533-4dad-8eee-3a0e8ad21140.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxMDQ4MTAsIm5iZiI6MTcwNzEwNDUxMCwicGF0aCI6Ii8yMzQwNDMzMi8zMDA4OTMzNTgtNzFjNzk2ZWUtZTUzMy00ZGFkLThlZWUtM2EwZThhZDIxMTQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA1VDAzNDE1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEzYjk3NThjMGRhYTU3YTNiYzBhMTc2ZTM1MjI2Y2E4MmI3OTNjODJiMGExMDg0Yjc3ZDZmYzk3MWVkMjFmNmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0RQ13M5_sfJk7hRq_guVqCQ40SFhkjfWymoYbRsUqVw) 是的，我已经安装完成😊

This is too cool. Can you share the EFI

**Comment by Ghost-Cavendish** [comment]
@ChenZesen Brother, what configuration has been modified
