### ISSUE TITLE
Can the built-in microphone in your computer work normally?

### ISSUE THREAD

**Issue by ChenZesen** [kalkmann/Legion-5600H-Hackintosh#22]
The built-in microphone in my computer can be recognized normally, but when I want to use it to record sound, it doesn't respond at all. 
Later, I tried to adapt to AppleALC.kext, but it still didn't work. In addition, the built-in microphone in Windows 11 can use recording to confirm that there is no problem with the hardware.

**Comment by Ghost-Cavendish** [comment]
Friends, can you share your EFI of 5800h+6600m, thank you

**Comment by ChenZesen** [comment]
> 朋友们，你能分享你5800h+6600m的EFI吗，谢谢

抱歉，由于我的网络处于防火墙之中，当我想要上传文件的时候它总是失败。如果你需要我的文件请等待我解决这个问题并上传

**Comment by ChenZesen** [comment]
> Friends, can you share your EFI of 5800h+6600m, thank you

抱歉，由于我的网络处于防火墙之中，当我想要上传文件的时候它总是失败。如果你需要我的文件请等待我解决这个问题并上传

**Comment by Ghost-Cavendish** [comment]
> > Friends, can you share your EFI of 5800h+6600m, thank you
> 
> 抱歉，由于我的网络处于防火墙之中，当我想要上传文件的时候它总是失败。如果你需要我的文件请等待我解决这个问题并上传

无需要，非常感谢您，能加微信发给我吗，微信号：hdbdbjjdvrj

**Comment by Ghost-Cavendish** [comment]
> > Friends, can you share your EFI of 5800h+6600m, thank you
> 
> 抱歉，由于我的网络处于防火墙之中，当我想要上传文件的时候它总是失败。如果你需要我的文件请等待我解决这个问题并上传

我需要，非常感谢您，能加微信发给我吗，微信号：hdbdbjjdvrj

**Comment by ChenZesen** [comment]
> > > Friends, can you share your EFI of 5800h+6600m, thank you
> > 
> > 
> > 抱歉，由于我的网络处于防火墙之中，当我想要上传文件的时候它总是失败。如果你需要我的文件请等待我解决这个问题并上传
> 
> 我需要，非常感谢您，能加微信发给我吗，微信号：hdbdbjjdvrj

https://lanban.lanzn.com/i0LfR1nfdhte

**Comment by Ghost-Cavendish** [comment]
为什么我安装完成后，硬盘用type-c硬盘盒连接电脑才不会在登录界面卡死，把固态硬盘装在m.2接口上会在登录界面卡死没法登录，不知道怎么会是？你有升级过bios版本吗。

**Comment by Ghost-Cavendish** [comment]
为什么我安装完成后，硬盘用type-c硬盘盒连接电脑才不会在登录界面卡死，把固态硬盘装在m.2接口上会在登录界面卡死没法登录，不知道怎么回事？你有升级过bios版本吗。

**Comment by kalkmann** [comment]
> The built-in microphone in my computer can be recognized normally, but when I want to use it to record sound, it doesn't respond at all. Later, I tried to adapt to AppleALC.kext, but it still didn't work. In addition, the built-in microphone in Windows 11 can use recording to confirm that there is no problem with the hardware.

Have you tested all possible layouts? You can try to build an applealc kext from the source, with the correct pin configurations. It is laborious and may have to be redone with each new version.

https://github.com/5T33Z0/AppleALC-Guides

https://brakintosh.gitbook.io/hackintosh/criando-layout-de-audio

https://github.com/F0x1c/AppleALC_Instructions

**Much easier, if the P2 microphone connection is essential in your workflow, is to buy a cheap usb audio dongle, it works independently of kexts:*

https://aliexpress.com/item/1005006010782653.html
