### ISSUE TITLE
iGPU HDMI Not Working

### ISSUE THREAD

**Issue by yasinari** [kalkmann/Legion-5600H-Hackintosh#23]
I managed to identify the internal graphics card with Nootedred, but the hdmi does not work at all. I cannot transfer images via Type-C. How can I solve this problem?

**Comment by kalkmann** [comment]
> I managed to identify the internal graphics card with Nootedred, but the hdmi does not work at all. I cannot transfer images via Type-C. How can I solve this problem?

Your laptop is not the same as mine, right? Your HDMI port may be connected to your laptop's DGPU (maybe an unsupported nvidia one).
