### ISSUE TITLE
A few remaining issues

### ISSUE THREAD

**Issue by hminhquan2002** [kalkmann/Legion-5600H-Hackintosh#24]
Dear kalkman,

First of all, I want to say thank you for all of your hard work in order to research and share your efi build with us. I just want to ask if you know any information about my remaining issues, or lucky some solution for them.

I have successfully installed a hackintosh on Acer Nitro 5 ANA-45 Ryzen 5 5600H.
I've followed these guides to install:
https://dortania.github.io/OpenCore-Install-Guide/prerequisites.html
https://chefkissinc.github.io/nred
https://github.com/kalkmann/Legion-5600H-Hackintosh (your guide for kexts and caveats)
(With few issues: DRM, hardware decoder/encoder accelerate and others are known nootedred bugs)

For DRM and hardware decoder, I use those command lines listed at the end of this guide but it can only fix them partially https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md

So I have a few questions regarding other problems which I haven't resolved yet
1. The USB 3.0 port stopped working and the backlight flashed randomly on macintosh boot
2. Long sleep time and then wake will cause the built-in monitor won't turn on
3. Imessages doesn't work with ethernet (cause I don't have a suitable wifi card)
I wonder if you have encountered the same bugs and thanks for your support

**Comment by kalkmann** [comment]
> Dear kalkman,
> 
> First of all, I want to say thank you for all of your hard work in order to research and share your efi build with us. I just want to ask if you know any information about my remaining issues, or lucky some solution for them.
> 
> I have successfully installed a hackintosh on Acer Nitro 5 ANA-45 Ryzen 5 5600H. I've followed these guides to install: https://dortania.github.io/OpenCore-Install-Guide/prerequisites.html https://chefkissinc.github.io/nred https://github.com/kalkmann/Legion-5600H-Hackintosh (your guide for kexts and caveats) (With few issues: DRM, hardware decoder/encoder accelerate and others are known nootedred bugs)
> 
> For DRM and hardware decoder, I use those command lines listed at the end of this guide but it can only fix them partially https://github.com/acidanthera/WhateverGreen/blob/master/Manual/FAQ.Chart.md
> 
> So I have a few questions regarding other problems which I haven't resolved yet
> 
> 1. The USB 3.0 port stopped working and the backlight flashed randomly on macintosh boot
> 2. Long sleep time and then wake will cause the built-in monitor won't turn on
> 3. Imessages doesn't work with ethernet (cause I don't have a suitable wifi card)
>    I wonder if you have encountered the same bugs and thanks for your support

Share your efi and complete hardware specs 👍

**Comment by hminhquan2002** [comment]
Here is my efi folder [EFI.zip](https://github.com/kalkmann/Legion-5600H-Hackintosh/files/14812788/EFI.zip)
I also used some command line as follow:
sudo pmset autopoweroff 0
sudo pmset powernap 0
sudo pmset standby 0
sudo pmset proximitywake 0
sudo pmset tcpkeepalive 0

My laptop specs: https://nanoreview.net/en/laptop/acer-nitro-5-an515-45
(Ryzen 5 5600H, GTX 1650M 4G, 8G of RAM)

**Comment by kalkmann** [comment]
> Here is my efi folder [EFI.zip](https://github.com/kalkmann/Legion-5600H-Hackintosh/files/14812788/EFI.zip) I also used some command line as follow: sudo pmset autopoweroff 0 sudo pmset powernap 0 sudo pmset standby 0 sudo pmset proximitywake 0 sudo pmset tcpkeepalive 0
> 
> My laptop specs: https://nanoreview.net/en/laptop/acer-nitro-5-an515-45 (Ryzen 5 5600H, GTX 1650M 4G, 8G of RAM)

I understood. you use nootedred with only integrated. unfortunately I don't have any experience with similar systems. but you will find many repositories here on git that use the integrated with nvidia disabled. I believe that most of your problems are related to this specific type of setup, in addition to the absence of Intel WiFi.

good luck in your build!

**Comment by hminhquan2002** [comment]
Alright, thank you for spending time

**Comment by hminhquan2002** [comment]
Update 31/03: fixed 1&2 using amdtscsync.kext complied with latest commits. 3 needs to call apple customer service. No more unknown issues and causes, hope everyone get good hacks

**Comment by kalkmann** [comment]
> Update 31/03: fixed 1&2 using amdtscsync.kext complied with latest commits. 3 needs to call apple customer service. No more unknown issues and causes, hope everyone get good hacks

Here, no luck with amdtscsync.kext with sleep. Great that you solved yours!

**Comment by hminhquan2002** [comment]
[CpuTscSync_AMD-1.1.1-2024-03-30_23.42.13.zip](https://github.com/kalkmann/Legion-5600H-Hackintosh/files/14815152/CpuTscSync_AMD-1.1.1-2024-03-30_23.42.13.zip)
Try this kext which is compiled by CorpGhost from AMD OSX discord forum

**Comment by kalkmann** [comment]
> > Update 31/03: fixed 1&2 using amdtscsync.kext complied with latest commits. 3 needs to call apple customer service. No more unknown issues and causes, hope everyone get good hacks
> 
> Here, no luck with amdtscsync.kext with sleep. Great that you solved yours!

I accidentally deleted your last comment (old people do shit!) Please repost so I can test the kext you mentioned. Thanks!

**Comment by kalkmann** [comment]
Yes, here, this new kext worked too (I think it's another new variant of cputscsync, not amdtscsync), I'm testing it on 14.4.1, it goes to sleep and comes back (but I still have to use the SSDT to turn off my USB ports to sleep).

I found the post from CorpGhost you mentioned: https://discord.com/channels/249992304503291905/263798638373896203/1223854953672736788

Now I'm going to connect the 4K monitor to the HDMI port to see if I'll suffer the same freezes in heavy GPU load (it was probably TSC/DGPU related).

Thank you very much for your discoveries!

**Comment by kalkmann** [comment]
With this new kext and connected to 4K external monitor, experienced a freeze before enter sleep, with only FCP and Chrome openned.

<img width="1375" alt="image" src="https://github.com/kalkmann/Legion-5600H-Hackintosh/assets/8891448/6eccf185-6c4e-4764-a74e-48a52325e950">

**Comment by kalkmann** [comment]
> Yes, here, this new kext worked too (I think it's another new variant of cputscsync, not amdtscsync), I'm testing it on 14.4.1, it goes to sleep and comes back (but I still have to use the SSDT to turn off my USB ports to sleep).
> 
> I found the post from CorpGhost you mentioned: https://discord.com/channels/249992304503291905/263798638373896203/1223854953672736788
> 
> Now I'm going to connect the 4K monitor to the HDMI port to see if I'll suffer the same freezes in heavy GPU load (it was probably TSC/DGPU related).
> 
> Thank you very much for your discoveries!

it was the same kext I was using, from Seey6's

<img width="818" alt="image" src="https://github.com/kalkmann/Legion-5600H-Hackintosh/assets/8891448/f21d5e1f-9a99-4df0-ae45-97d0f586c24b">
