### ISSUE TITLE
How to enable DRM in your AMD GPU?

### ISSUE THREAD

**Issue by Aliezan** [kalkmann/Legion-5600H-Hackintosh#25]
Hi! I just wanna ask how do you determine the value of DeviceProperties containing CFG_LINKED_MAP to enable DRM on macOS.

I already installed macOS Ventura on my Legion 5 15ARH05 but the DRM fails showed by VDADecoder failed.
an answer will be highly appreciated, thank you!

**Comment by kalkmann** [comment]
It was determined by trial and error... What is your dgpu?

**Comment by Aliezan** [comment]
I'm using AMD Ryzen 5 iGPU, is it possible? or it's only works on dGPU?
![Screenshot 2024-04-05 at 07 32 38](https://github.com/kalkmann/Legion-5600H-Hackintosh/assets/115769623/4be6974c-e141-4b24-bfd3-a00ff36586d2)

**Comment by kalkmann** [comment]
No way 😑
