### ISSUE TITLE
A few questions about Patch "Delete to fix SRFZ namespace"

### ISSUE THREAD

**Issue by hoaug-tran** [kalkmann/Legion-5600H-Hackintosh#26]
Hello,

Thank you for a wonderfully successful project with your machine

I will refer to your EFI to see if I need to optimize something for my machine. And I discovered the "Delete to fix SRFZ namespace" Patch. May I know if it has any effect? It seems to me that it is not used in conjunction with any SSDT?. Can you explain to me why we use that Patch and what its effects are?

Thank you

Have a nice day !

**Comment by kalkmann** [comment]
It is a specific patch for the ACPI of this notebook. Just cosmetic related to verbose boot. 

Good hack!
