### ISSUE TITLE
Trackpad does not work

### ISSUE THREAD

**Issue by MinecraftNerrd1337** [kalkmann/Legion-5600H-Hackintosh#29]
My Legion 5 is slightly different, it has the synaptics version of the trackpad. Looks like DSDT supports both the ELAN and synaptics.
Could you please send me your DSDT?

**Comment by kalkmann** [comment]
[System DSDT-G9CN37WW.dsl.zip](https://github.com/kalkmann/Legion-5600H-Hackintosh/files/15390217/System.DSDT-G9CN37WW.dsl.zip)

**Comment by MinecraftNerrd1337** [comment]
Trackpad in DSDT is identical to mine. I'm assuming you have the Elan model and not the Synaptics.
Mine doesn't even show up as being under I2C in IORegExplorer, but rather under AppleACPIPlatformExpert or whatever.
Even though it's definitely under I2C when I check in Windows, and I use SSDT-XOSI

**Comment by kalkmann** [comment]
You use SSDT-HPET?

**Comment by MinecraftNerrd1337** [comment]
Yes!
My trackpad's ID in Windows is SYNA2BA6. CID is PNP0C50 so should be I2C HID but does not work...

**Comment by kalkmann** [comment]
> Yes! My trackpad's ID in Windows is SYNA2BA6. CID is PNP0C50 so should be I2C HID but does not work...

In my experience with this laptop here, SSDT-HPET generated by SSDTTime conflicts with the trackpad operation. So I don't use this ACPI patch.

Also remembering that I use Kext created by Chefkiss:

https://chefkissinc.github.io/Extras/Kexts/VoodooI2C.zip

**Comment by MinecraftNerrd1337** [comment]
Yes, VoodooI2Cservices and VoodooGPIO are both attaching for me, I used the right kext.
It's just that my trackpad (whose CID is PNP0C50 as should be) isn't attaching, even when I force polling.

I do use HPET, so I'll try without

**Comment by MinecraftNerrd1337** [comment]
Fixed it! Thank you so much!
Now only sleep is broken, but I believe it's because of NootedRed, since I have 5800H RTX 3060 and of course I just disable the RTX
