### ISSUE TITLE
I HAVE LENOVO IDEAPAD GAMING 3 THIS DOESNT WORK IN IT LOG EXITBS START ERROR APPEAR

### ISSUE THREAD

**Issue by mhmd2234** [kalkmann/Legion-5600H-Hackintosh#3]
I HAVE THE SAME CPU BUT DIFFRENT GPU IT IS 3060

**Comment by UsetUset2244** [comment]
still stuck on the #[EB|LOG:EXITBS:START]. cant you help me @kalkmann

**Comment by kalkmann** [comment]
Nvidia 3060 is incompatible with macos. No way...
