### ISSUE TITLE
AMD Power Gadget issue

### ISSUE THREAD

**Issue by SheltangW** [kalkmann/Legion-5600H-Hackintosh#30]
Bro, may I take a look at your AMD Power Gadget speed steps settings? I have a laptop with the same 5600h processor, but it doesn't work when selecting different speed step with AMD Power Gadget. Do you have a customized PState?

**Comment by kalkmann** [comment]
> Bro, may I take a look at your AMD Power Gadget speed steps settings? I have a laptop with the same 5600h processor, but it doesn't work when selecting different speed step with AMD Power Gadget. Do you have a customized PState?

I never customized. What would be the objective, overclocking?
