### ISSUE TITLE
Installation and Formatting Issues with Laptop Model

### ISSUE THREAD

**Issue by RaulKong898** [kalkmann/Legion-5600H-Hackintosh#31]
I have the same laptop model, and I want to mention an error. When I try to install it, it shows that it's installing, but then the installation freezes and doesn't complete. The same thing happens when I try to format the partition; it freezes during the first formatting mode, but the partition gets formatted. Is there a solution?

**Comment by RaulKong898** [comment]
Could you make a video tutorial that is new to the hackintosh world?

**Comment by kalkmann** [comment]
Try https://github.com/ducviet5138/Hackintosh-Legion-5

Sorry for the delay 😞
