### ISSUE TITLE
no mac os install on boot

### ISSUE THREAD

**Issue by Nelio153** [kalkmann/Legion-5600H-Hackintosh#37]
hello

i try to rebuild your efi to my lenovo, but no mac os intall picker on boot, idea ?

mine is lenovo legion pro 16ACH6H with cpu 5800H and gpu 3070, try efi of ducviet5138  same problem no picker mac os install on boot

**Comment by kalkmann** [comment]
My EFI is configured to work with AMD dGPU. If you also tried with another EFI and had the same problem, it seems that the problem is in the way the installation USB stick was created. Try following the guide: https://dortania.github.io/OpenCore-Install-Guide/installer-guide/

**Comment by Nelio153** [comment]
i have problem with your efi and efi guy fork for nvidia gpu, no icon mac
os install on boot, only windows and if press space nvram...only

**Comment by kalkmann** [comment]
First try creating a basic installation USB stick from scratch.

Try this: https://chefkissinc.github.io/guides/hackintosh/

**Comment by Nelio153** [comment]
thanks for this link which reminds some fundamentals, but I already have some hackintosh experience such as my T430 under ventura it seems to be old and the screen resolution is not beautiful, the problem is that for this one I can not have at boot the icon install macos with your efi, I modified the number of cpu with proper tree but nothing did same problem have deactivated something?

57 / 5 000
I have two USB keys, one under Sonoma and the other under Sequoia.

**Comment by kalkmann** [comment]
There is nothing special about these EFIs that would prevent them from detecting a MacOS installation or system (at least on my machine).

Test the same USB stick on the other machine, with and without the 2 USB kexts for that EFI. That could be it.

**Comment by Nelio153** [comment]
it's surprising I tried usb from my t430 on this legion it's where it displays the installation icon, I tried usb from this legion on t430 it's ok it displays the icon, it's very weird I also tried removing 2 kext usb same symptom,I removed 16 GB of RAM, same thing, I removed SSD, same thing

**Comment by kalkmann** [comment]
Weird!

**Comment by kalkmann** [comment]
Have you tried with the same USB kext present on the t530 pendrive? (if there is one)

**Comment by Nelio153** [comment]
I always keep a USB key to boot the system in case of a problem, moreover when the configuration is stabilized I make a clone with CCC of my system ready for use, with your efi on the Legion impossible to have the mac installation icon, on the T430 it's ok
