### ISSUE TITLE
Why XHC1 must be turned off

### ISSUE THREAD

**Issue by akwangl** [kalkmann/Legion-5600H-Hackintosh#5]
I've tried to turn it on a few times to get into the system, but this doesn't always get in. Do you have any research on this

**Comment by kalkmann** [comment]
As far as I know, no one has yet found a solution to leave the 2 controllers enabled. This was a solution I found (disabling the XHC1 via UMAF penboot) for my dependency on constantly using USB storage. If you don't use USB storage, you can use the GenericUSBXHCI kext with the 2 active controllers (only for mouse, etc).
