### ISSUE TITLE
Stuck Apple logo with empty bar

### ISSUE THREAD

**Issue by daniilvohromeev** [kalkmann/Legion-5600H-Hackintosh#6]
Maybe you know what the problem is? Starting from apple.recovery.boot

**Comment by daniilvohromeev** [comment]
My laptop is exactly like yours

**Comment by kalkmann** [comment]
> Maybe you know what the problem is? Starting from apple.recovery.boot

You are booting with only discrete graphics (only RX 6600 enabled, no hybrid graphics)? Boot with -v and post image of screen freeze.

**Comment by daniilvohromeev** [comment]
That's right. Rx6000 is disabled in BIOS, XCH too. But to see the .dmg I changed ScanPolicy -> 0 in config.plist. That's the only thing I changed.![image](https://github.com/kalkmann/Legion-5600H-Hackintosh/assets/62345534/69e87991-9571-488b-82c1-43d346ff35ec)

**Comment by daniilvohromeev** [comment]
Sorry, I mistyped. Integrated graphics off and RX6000 turn on
Log from opencore:
84:934 00:026 OCAK: 64-bit algrey | Force cpuid_cores_per_package to constant (user-specified) | 13.3+ replace count - 1
84:960 00:025 OC: Kernel patcher result 3 for kernel (algrey | Force cpuid_cores_per_package to constant (user-specified) | 13.3+) - Success
84:988 00:028 OCAK: 64-bit algrey | _commpage_populate | Remove rdmsr | 10.13+ replace count - 1
85:014 00:026 OC: Kernel patcher result 4 for kernel (algrey | _commpage_populate | Remove rdmsr | 10.13+) - Success
85:042 00:027 OCAK: 64-bit algrey | _cpuid_set_cache_info | Set CPUID proper instead of 4 | 10.13+ replace count - 1
85:068 00:026 OC: Kernel patcher result 5 for kernel (algrey | _cpuid_set_cache_info | Set CPUID proper instead of 4 | 10.13+) - Success
85:096 00:027 OCAK: 64-bit algrey | _cpuid_set_generic_info | Remove wrmsr(0x8B) | 10.13+ replace count - 1
85:122 00:026 OC: Kernel patcher result 6 for kernel (algrey | _cpuid_set_generic_info | Remove wrmsr(0x8B) | 10.13+) - Success
85:150 00:028 OCAK: 64-bit algrey | _cpuid_set_generic_info | Replace rdmsr(0x8B) with constant 186 | 10.13+ replace count - 1
85:177 00:026 OC: Kernel patcher result 7 for kernel (algrey | _cpuid_set_generic_info | Replace rdmsr(0x8B) with constant 186 | 10.13+) - Success
85:205 00:027 OCAK: 64-bit algrey | _cpuid_set_generic_info | Set flag=1 | 10.13+ replace count - 1
85:231 00:026 OC: Kernel patcher result 8 for kernel (algrey | _cpuid_set_generic_info | Set flag=1 | 10.13+) - Success
85:261 00:029 OCAK: 64-bit algrey | _cpuid_set_generic_info | Disable check to allow leaf7 | 10.13+ replace count - 1
85:288 00:027 OC: Kernel patcher result 9 for kernel (algrey | _cpuid_set_generic_info | Disable check to allow leaf7 | 10.13+) - Success
85:314 00:026 OC: Kernel patcher skips kernel (algrey | _cpuid_set_info | GenuineIntel to AuthenticAMD | 10.13-11.0) patch at 10 due to version 170000 <= 220500 <= 209999
85:341 00:026 OCAK: 64-bit Goldfish64, algrey | Bypass GenuineIntel check panic | 12.0+ replace count - 1
85:367 00:025 OC: Kernel patcher result 11 for kernel (Goldfish64, algrey | Bypass GenuineIntel check panic | 12.0+) - Success
85:432 00:064 OC: Kernel patcher skips kernel (algrey | _cpuid_set_cpufamily | Force CPUFAMILY_INTEL_PENRYN | 10.13-11.2) patch at 12 due to version 170000 <= 220500 <= 200300
85:458 00:026 OCAK: 64-bit algrey | _cpuid_set_cpufamily | Force CPUFAMILY_INTEL_PENRYN | 11.3+ replace count - 1
85:485 00:026 OC: Kernel patcher result 13 for kernel (algrey | _cpuid_set_cpufamily | Force CPUFAMILY_INTEL_PENRYN | 11.3+) - Success
85:545 00:060 OCAK: 64-bit algrey | _i386_init | Remove 3 rdmsr calls | 10.13+ replace count - 3
85:571 00:026 OC: Kernel patcher result 14 for kernel (algrey | _i386_init | Remove 3 rdmsr calls | 10.13+) - Success
85:599 00:027 OCAK: 64-bit algrey, XLNC | Remove version check and panic | 10.13+ replace count - 1
85:625 00:025 OC: Kernel patcher result 15 for kernel (algrey, XLNC | Remove version check and panic | 10.13+) - Success
85:653 00:028 OCAK: 64-bit Visual | thread_quantum_expire, thread_unblock, thread_invoke | Remove non-monotonic time panic | 12.0+ replace count - 3
85:680 00:026 OC: Kernel patcher result 18 for kernel (Visual | thread_quantum_expire, thread_unblock, thread_invoke | Remove non-monotonic time panic | 12.0+) - Success
85:710 00:029 OCAK: 64-bit Visual | thread_invoke, thread_dispatch | Remove non-monotonic time panic | 12.0+ replace count - 2
85:737 00:026 OC: Kernel patcher result 19 for kernel (Visual | thread_invoke, thread_dispatch | Remove non-monotonic time panic | 12.0+) - Success
85:820 00:083 OCAK: 64-bit Shaneee | _mtrr_update_action | Fix PAT | 10.13+ replace count - 2
85:846 00:025 OC: Kernel patcher result 21 for kernel (Shaneee | _mtrr_update_action | Fix PAT | 10.13+) - Success
85:946 00:100 OCAK: Patching invalid size 146FFD with 227B000 for com.apple.iokit.IO80211FamilyLegacy
85:973 00:026 OCAK: Patching invalid size 33FFA with 2969000 for com.apple.driver.AppleMobileFileIntegrity
86:000 00:027 OCAK: Patching invalid size 9FF7 with 25FC000 for com.apple.iokit.CoreAnalyticsFamily
86:039 00:038 OCAK: Patching invalid size 78FD0 with C8B000 for com.apple.kec.corecrypto
86:076 00:036 OCAK: Patching invalid size 9FFA with 251E000 for com.apple.kext.CoreTrust
86:111 00:035 OCAK: Patching invalid size 1EFF5 with 2AA2000 for com.apple.security.AppleImage4
86:150 00:038 OCAK: Patching invalid size 22FF5 with CBC000 for com.apple.driver.corecapture
86:191 00:040 OCAK: Patching invalid size 16FF4 with 171B000 for com.apple.iokit.IONetworkingFamily
86:230 00:039 OCAK: Patching invalid size 2D000 with 13CE000 for com.apple.iokit.IOSkywalkFamily
86:296 00:066 OCAK: Patching invalid size 5000 with 14C1000 for com.apple.driver.mDNSOffloadUserClient
86:351 00:054 OCAK: Patching invalid size 32000 with 14BA000 for com.apple.iokit.IOPCIFamily
86:447 00:096 OCAK: Local relocs 2712 on FFFFFF800434B000
86:485 00:037 OC: Prelinked injection AirportItlwm.kext (AirportItlwm.kext) - Success
86:521 00:035 OC: Prelinked injection AirportItlwm.kext v2.2.0
86:556 00:035 OC: Prelinked injection AppleMCEReporterDisabler.kext (AppleMCEReporterDisabler.kext) - Success
86:591 00:034 OC: Prelinked injection AppleMCEReporterDisabler.kext v1.2
86:631 00:040 OCAK: Local relocs 852 on FFFFFF800529C000
86:732 00:100 OC: Prelinked injection Lilu.kext (Lilu.kext) - Success
86:767 00:035 OC: Prelinked injection Lilu.kext v1.6.6
86:806 00:038 OCAK: Local relocs 624 on FFFFFF8005326000
86:842 00:036 OC: Prelinked injection NVMeFix.kext (NVMeFix.kext) - Success
86:877 00:034 OC: Prelinked injection NVMeFix.kext v1.1.0
86:917 00:040 OCAK: Local relocs 469 on FFFFFF8005333000
86:954 00:036 OC: Prelinked injection RealtekRTL8111.kext (RealtekRTL8111.kext) - Success
86:989 00:035 OC: Prelinked injection RealtekRTL8111.kext v2.4.2
87:028 00:038 OCAK: Local relocs 311 on FFFFFF80053B7000
87:064 00:035 OC: Prelinked injection RestrictEvents.kext (RestrictEvents.kext) - Success
87:099 00:034 OC: Prelinked injection RestrictEvents.kext v1.1.2
87:136 00:037 OCAK: Patching invalid size FFF with 103D000 for com.apple.driver.AppleUSBHostMergeProperties
87:175 00:038 OCAK: Local relocs 309 on FFFFFF80053C8000
87:211 00:035 OC: Prelinked injection USBToolBox.kext (USBToolBox.kext) - Success
87:246 00:035 OC: Prelinked injection USBToolBox.kext v1.1.1
87:282 00:035 OC: Prelinked injection UTBMap.kext (UTBMap.kext) - Success
87:317 00:035 OC: Prelinked injection UTBMap.kext v1.1
87:354 00:036 OCAK: Patching invalid size 2000 with 192A000 for com.apple.iokit.IOACPIFamily
87:433 00:079 OCAK: Local relocs 504 on FFFFFF80053D1000
87:470 00:036 OC: Prelinked injection VirtualSMC.kext (VirtualSMC.kext) - Success
87:504 00:034 OC: Prelinked injection VirtualSMC.kext v1.3.2
87:546 00:041 OCAK: Local relocs 1579 on FFFFFF80053FA000
87:584 00:038 OC: Prelinked injection VoodooPS2Controller.kext (VoodooPS2Controller.kext) - Success
87:619 00:035 OC: Prelinked injection VoodooPS2Controller.kext v2.3.5
87:658 00:038 OCAK: Patching invalid size 62000 with 17EF000 for com.apple.iokit.IOHIDFamily
87:695 00:036 OCAK: Patching invalid size 2FF8 with 1478000 for com.apple.iokit.IOReportFamily
87:758 00:063 OCAK: Local relocs 346 on FFFFFF8005413000
87:793 00:035 OC: Prelinked injection VoodooPS2Controller.kext\Contents\PlugIns\VoodooPS2Keyboard.kext (VoodooPS2Keyboard.kext) - Success
87:829 00:035 OC: Prelinked injection VoodooPS2Controller.kext\Contents\PlugIns\VoodooPS2Keyboard.kext v2.3.5
87:873 00:044 OCAK: Local relocs 5871 on FFFFFF8005420000
87:914 00:041 OC: Prelinked injection VoodooI2C.kext\Contents\PlugIns\VoodooGPIO.kext (VoodooGPIO.kext) - Success
87:949 00:035 OC: Prelinked injection VoodooI2C.kext\Contents\PlugIns\VoodooGPIO.kext v1.1
87:988 00:039 OCAK: Local relocs 602 on FFFFFF8005465000
88:024 00:036 OC: Prelinked injection VoodooI2C.kext\Contents\PlugIns\VoodooI2CServices.kext (VoodooI2CServices.kext) - Success
88:060 00:035 OC: Prelinked injection VoodooI2C.kext\Contents\PlugIns\VoodooI2CServices.kext v1
88:101 00:041 OCAK: Local relocs 1338 on FFFFFF8005470000
88:139 00:037 OC: Prelinked injection VoodooI2C.kext\Contents\PlugIns\VoodooInput.kext (VoodooInput.kext) - Success
88:174 00:034 OC: Prelinked injection VoodooI2C.kext\Contents\PlugIns\VoodooInput.kext v1.1.4
88:211 00:037 OCAK: Patching invalid size DFE0 with F04000 for com.apple.kec.Libm
88:251 00:040 OCAK: Local relocs 686 on FFFFFF800548B000
88:287 00:035 OC: Prelinked injection AMDRyzenCPUPowerManagement.kext (AMDRyzenCPUPowerManagement.kext) - Success
88:322 00:034 OC: Prelinked injection AMDRyzenCPUPowerManagement.kext v0.7.1
88:407 00:085 OCAK: Local relocs 5769 on FFFFFF80054AB000
88:460 00:052 OC: Prelinked injection AppleALC.kext (AppleALC.kext) - Success
88:494 00:034 OC: Prelinked injection AppleALC.kext v1.8.3
88:536 00:041 OCAK: Local relocs 322 on FFFFFF8005659000
88:571 00:035 OC: Prelinked injection SMCAMDProcessor.kext (SMCAMDProcessor.kext) - Success
88:606 00:035 OC: Prelinked injection SMCAMDProcessor.kext v1
88:643 00:036 OCAK: Patching invalid size FFE with 13E3000 for com.apple.iokit.IOSMBusFamily
88:684 00:041 OCAK: Local relocs 824 on FFFFFF8005669000
88:721 00:036 OC: Prelinked injection SMCBatteryManager.kext (SMCBatteryManager.kext) - Success
88:755 00:034 OC: Prelinked injection SMCBatteryManager.kext v1.3.2
88:810 00:054 OCAK: Local relocs 3119 on FFFFFF8005683000
88:850 00:040 OC: Prelinked injection VoodooI2C.kext (VoodooI2C.kext) - Success
88:885 00:035 OC: Prelinked injection VoodooI2C.kext v2.8
88:948 00:062 OCAK: Local relocs 4122 on FFFFFF80056AE000
88:990 00:042 OC: Prelinked injection VoodooI2CHID.kext (VoodooI2CHID.kext) - Success
89:025 00:035 OC: Prelinked injection VoodooI2CHID.kext v1
89:060 00:034 OC: Prelink size 90054656 kext offset 69513216 reserved 20541440
89:095 00:035 OCAK: KC TEXT is 65536 bytes with 62328 Mach-O headers need 1368
89:148 00:053 OCAK: Failed to pk find com.apple.driver.AppleIntelCPUPowerManagement - Not Found
89:183 00:034 OCAK: [OK] Skipping dummy AppleIntelCPUPowerManagement patch on 220500
89:218 00:035 OCAK: 64-bit CaseySJ | probeBusGated | Disable 10 bit tags | 12.0+ replace count - 1
89:253 00:035 OC: Prelinked patcher result 16 for com.apple.iokit.IOPCIFamily (CaseySJ | probeBusGated | Disable 10 bit tags | 12.0+) - Success
89:367 00:113 OC: Prelinked status - Success
89:663 00:296 AAPL: #[EB.LD.LKFS|-?] Ok(0)
89:707 00:043 AAPL: #[EB.LD.LKC|-?] Ok(0)
89:774 00:066 AAPL: #[EB|BST:REV1]
89:817 00:043 AAPL: #[EB|CSR:OUT] 0x000007C7
89:863 00:046 AAPL: #[EB.BST.FBS|+]
89:907 00:043 AAPL: #[EB.BST.FBS|ADSZ] 0
89:950 00:043 AAPL: #[EB.BST.FBS|KSSZ] 0
89:994 00:043 AAPL: #[EB|SB:SBGMFNS] j223ap.im4m
90:038 00:044 AAPL: #[EB|RH:PF] usr\standalone\OS.dmg.root_hash
90:082 00:043 AAPL: #[EB|RH:MF] <"usr\\standalone\\OS.dmg.root_hash.j223ap.im4m">
90:126 00:043 AAPL: #[EB.LD.LF|IN] 0 1 <"usr\\standalone\\OS.dmg.root_hash"> <"0">
90:174 00:048 AAPL: #[EB.LD.OFS|OPEN!] Err(0xE) <"usr\\standalone\\OS.dmg.root_hash">
90:218 00:043 AAPL: #[EB.RH.LRH|P!] Err(0xE) <- EB.LD.LF
90:261 00:043 AAPL: #[EB.BST.FBS|!] Err(0xE) <- EB.RH.LRH
90:296 00:034 OCSMC: SmcReadValue Key 4D535463 Size 1
90:331 00:035 OCSMC: SmcReadValue Key 4D534163 Size 2
90:375 00:043 AAPL: #[EB|LOG:DT] 2023-07-20T15:18:41
90:419 00:043 AAPL: #[EB|LOG:EXITBS:START] 2023-07-20T15:18:41

**Comment by kalkmann** [comment]
We have same BIOS version (G9CN32WW)?

**Comment by daniilvohromeev** [comment]
Yep.![image](https://github.com/kalkmann/Legion-5600H-Hackintosh/assets/62345534/532f098c-4d1f-4d96-9484-254cd4aff208)

**Comment by daniilvohromeev** [comment]
G9CN33WW

**Comment by kalkmann** [comment]
Your bios is one version higher than mine. I already tried to update mine and had problems to boot hack.

So I had the bad idea of downgrading and bricked the bios. I had to buy a reprogrammer to go back to the previous version and I don't mess with bios any time soon.

Sorry for not being able to help more... you can try to get help on discord and forum https://forum.amd-osx.com/

**Comment by daniilvohromeev** [comment]
thanks for trying to help

**Comment by kalkmann** [comment]
If you get a compatibility solution with this BIOS version, please let me know. Thanks.

**Comment by nickcomua** [comment]
Hi i have same problem, currently i have G9CN22WW bios version but i don't know how to update to G9CN36WW. There are only G9CN36WW version in Lenovo support website.

**Comment by Brilliantsaidso** [comment]
seeeeeWWW
