### ISSUE TITLE
Problem of Trackpad

### ISSUE THREAD

**Issue by junzhin** [kalkmann/Legion-5600H-Hackintosh#7]
I am using the legion-5800H with a discrete card of 3060, I adjusted some content in your efi, it works very well except for the built-in trackpad. Could you suggest a reason why this is case?

Thank you for your help!

**Comment by kalkmann** [comment]
> I am using the legion-5800H with a discrete card of 3060, I adjusted some content in your efi, it works very well except for the built-in trackpad. Could you suggest a reason why this is case?
> 
> Thank you for your help!

maybe it's not even the same hardware. With mine, if I generate ssdt-hpet (with its patches of acpi renames) with the ssdtime tool, the trackpad doesn't work.

**Comment by TongDucThanhNam** [comment]
> I am using the legion-5800H with a discrete card of 3060, I adjusted some content in your efi, it works very well except for the built-in trackpad. Could you suggest a reason why this is case?
> 
> Thank you for your help!

Can you share your EFI too, please? My specs is R5 5600H and RTX 3060 and i don't have experience to config EFI. Thank you very much.

**Comment by kalkmann** [comment]
> > > I am using the legion-5800H with a discrete card of 3060, I adjusted some content in your efi, it works very well except for the built-in trackpad. Could you suggest a reason why this is case?
> > > Thank you for your help!
> > 
> > 
> > maybe it's not even the same hardware. With mine, if I generate ssdt-hpet (with its patches of acpi renames) with the ssdtime tool, the trackpad doesn't work.
> 
> What's your hardware model? Mine is ELAN06FA ![image](https://user-images.githubusercontent.com/115403380/259309960-efec8185-190b-454e-ad0f-6b54dcbb1d44.png) Also, I generate ssdt-hpet patch with ssdtime tool, What is the correct method?

![image](https://github.com/kalkmann/Legion-5600H-Hackintosh/assets/8891448/7fc87a67-f47c-4c90-8c27-3bc1b6b14c8d)

The same!

Test with this kext from noot site (same I´m using in last EFI update): https://nootinc.github.io/Extras/Kexts/VoodooI2C.zip
